### PR TITLE
use correct kinovar marker, and extract images

### PR DESCRIPTION
**Pull request by pgmmpk**

### CODE REVIEW

**Review by 0xGeorgii — COMMENTED** [review]
Is it possible to embed an image into an MD?

**Comment by pgmmpk** [comment]
@GeorgePlotnikov 
No, Markdown always uses image links (just like HTML does). There is no way to embed
image into the Markdown text.

I am thinking of changing the output format to ZIP to be able to pack markdown text and all references images in a single file

**Comment by 0xGeorgii** [comment]
@pgmmpk does it make sense? Who will be able to works with a such container? Should be developed a suitable functionality. I can be done, definitely

**Comment by pgmmpk** [comment]
Not sure I understand you. ZIP or TAR containers are quire common, I do not expect that anyone would object having markdown+images packed in a ZIP (or TAR).

Currently images will be created in a separate sub-directory named `Pictures` of the markdown file's parent directory. The problem with this approach is that these files can be overwritten accidentally by the next extraction job...

cc @typiconman

**Comment by typiconman** [comment]
Yes, right now we have the directory structure:
`BookName` (contains metadata)
`BookName/chapters` (contains the text)
so we can add
`BookName/images` (contains any associated images)

I don't quite follow what is being overwritten. At the ODT2MD level? Or at the MD <-> XML level?

**Comment by pgmmpk** [comment]
@typiconman I am looking at this tool purely from the UX perspective:

Input is a **single** file, `sample.odt`

On command line we specify a **single** output file, named `sample.md`.

This is all good and very explicit and user expects `sample.odt` to be converted to `sample.md`.

However, if there are any images in the `sample.odt`, current tool will **implicitly** create `Pictures` sub-directory and extract some picture files there (btw, I am just using what ODT uses for image directory, its not me who decides to name it as `Pictures`)

Now, if user wants also to convert `sample2.odt` to `sample2.md`, and place `sample2.md` in the same directory as `sample.md`, then tool will do just that. However, if `sample.odt` has image `Pictures/img1.png`,  and `sample2.odt` happens to have an image with the same name, then
implicit image extraction will silently override the first one.

Less surprising behavior is when we convert one file to one file, e.g. ODT to ZIP.

Separately, we may want a flag that controls the name of the image directory...

**Comment by typiconman** [comment]
@pgmmpk That makes sense. Then I guess we need to output to ZIP. The alternative is temporary file names, e.g. `Picures_{random}`.

**Comment by 0xGeorgii** [comment]
@pgmmpk i meant you drop an MD with pictures in a container. And you can do it with all pages without any overriding problems (use page number as pre/post fix). And open it directly from web server / plugin and perform all needed transformation actions inside a ‘plugin’ (on the fly). Does it clear now?

**Comment by pgmmpk** [comment]
@GeorgePlotnikov 
> Does it clear now?

No, not really. Not sure why we are talking web, server and plugin.

This is just a CLI tool to do a one-time job of converting an ODT file to MD. There is no plans to make a web service out of it.

As of now, I do not change the names of the images. Within one ODT the names are obviously unique. Merging together ODT or MD files is a completely different activity, that is best delegated to the other tool. For now I just use ODT image names as-is in the Markdown.

**Comment by pgmmpk** [comment]
@typiconman @GeorgePlotnikov 
I changed CLI to generate ZIP with MD and (optional) images. Please, review again.

**Review by typiconman — APPROVED** [review]
LGTM.

However, I'm having no luck installing and running the tool. I must have some kind of problem with my Python?
Here is what I get:

```
$ python3.7 -m venv .venv
$ . .venv/bin/activate
(.venv) $ pip install -r requirements.txt 
Collecting regex~=2019.5.25 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/77/3f/cf89d346dd73f0f5eb118ff3ec0d9f3760f1ea85e2ede9eecac9648e0172/regex-2019.05.25.tar.gz
Collecting lxml~=4.3.3 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/66/20/49201c7bcb1c92942ac98658b09fb4a0c0dcd064d439489349bc5891207c/lxml-4.3.3-cp37-cp37m-manylinux1_x86_64.whl (5.7MB)
    100% |████████████████████████████████| 5.7MB 189kB/s 
Collecting lxmlx~=1.1.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/dc/a3/899faf1fadb08c131c195c40c1da33d9f5e8c7a7375a7db243d059a3b41b/lxmlx-1.1.2-py2.py3-none-any.whl
Building wheels for collected packages: regex
  Running setup.py bdist_wheel for regex ... error
  Complete output from command /home/sasha/Documents/odt2md/.venv/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n172jp52/regex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpv99gjs3apip-wheel- --python-tag cp37:
  BASE_DIR is /tmp/pip-build-n172jp52/regex
  /home/sasha/Documents/odt2md/.venv/lib/python3.7/site-packages/setuptools/dist.py:397: UserWarning: Normalizing '2019.05.25' to '2019.5.25'
    normalized_version,
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for regex
  Running setup.py clean for regex
Failed to build regex
Installing collected packages: regex, lxml, lxmlx
  Running setup.py install for regex ... done
Successfully installed lxml-4.3.3 lxmlx-1.1.2 regex-2019.5.25
```
Testing:
```
(.venv) $ pytest .
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.5.0, py-1.8.0, pluggy-0.12.0
rootdir: /home/sasha/Documents/odt2md
collected 0 items / 5 errors                                                   

==================================== ERRORS ====================================
__________________ ERROR collecting odt2md/test/test_block.py __________________
ImportError while importing test module '/home/sasha/Documents/odt2md/odt2md/test/test_block.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
odt2md/test/test_block.py:3: in <module>
    from odt2md.block import parse_blocks, ImageBlock, TextBlock, Span
E   ModuleNotFoundError: No module named 'odt2md'
_________________ ERROR collecting odt2md/test/test_escape.py __________________
ImportError while importing test module '/home/sasha/Documents/odt2md/odt2md/test/test_escape.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
odt2md/test/test_escape.py:1: in <module>
    from odt2md.util import escape
E   ModuleNotFoundError: No module named 'odt2md'
____________ ERROR collecting odt2md/test/test_is_single_letter.py _____________
ImportError while importing test module '/home/sasha/Documents/odt2md/odt2md/test/test_is_single_letter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
odt2md/test/test_is_single_letter.py:1: in <module>
    from odt2md.util import is_single_letter
E   ModuleNotFoundError: No module named 'odt2md'
____________ ERROR collecting odt2md/test/test_split_into_lines.py _____________
ImportError while importing test module '/home/sasha/Documents/odt2md/odt2md/test/test_split_into_lines.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
odt2md/test/test_split_into_lines.py:1: in <module>
    from odt2md.util import split_into_lines
E   ModuleNotFoundError: No module named 'odt2md'
__________________ ERROR collecting odt2md/test/test_style.py __________________
ImportError while importing test module '/home/sasha/Documents/odt2md/odt2md/test/test_style.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
odt2md/test/test_style.py:3: in <module>
    from odt2md.style import parse_styles, TextStyle, ParaStyle
E   ModuleNotFoundError: No module named 'odt2md'
!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 5 error in 0.08 seconds ============================
```

**Comment by pgmmpk** [comment]
@typiconman 

1. Before doing `pip install -r requirements.txt`, please do 'pip install wheel`. This should allow installing binary packages
2. `pytest` does not understand module structure. To help it, do `export PYTHONPATH=.` before
running pytest.

I updated the README.md

Please, confirm it works.

**Comment by typiconman** [comment]
@pgmmpk Install and test now works.

I tested conversion on the `sergius_example1.odt` file, and it seems to work well!

**Pull request merged**
